import type { OnboardingRawAnswers } from "@/types/onboarding";

export const onboardingDemoData: OnboardingRawAnswers = {
  q1: "Clínica Dental Sonrisa Perfecta",
  q2: "Somos una clínica dental especializada en odontología general, estética, ortodoncia e implantes. Atendemos pacientes que buscan tratamientos confiables, claros y con acompañamiento cercano.",
  q3: "Salud",
  q4: "Bogotá",
  q5: "Lunes a viernes 8am–6pm, sábados 8am–1pm",
  q6: "+573102223344",
  q7: "https://sonrisaperfecta.demo · @sonrisaperfecta",
  q8: "Valentina",
  q9: "Cercano y amigable — conversacional, cálido, como un asesor de confianza",
  q10: "Siempre usted",
  q11: "No prometer resultados médicos garantizados.\nNo usar lenguaje alarmista.",
  q12: "Con gusto le ayudamos a cuidar su sonrisa.\nLa valoración profesional es el primer paso.",
  q13: "Hola, soy Valentina de Clínica Dental Sonrisa Perfecta. Con gusto le ayudo a encontrar el tratamiento indicado y agendar una valoración con nuestro equipo.",
  q14: "P: ¿Cuánto cuesta la valoración?\nR: La valoración inicial cuesta $80.000 y permite definir el tratamiento recomendado.\n\nP: ¿Manejan financiación?\nR: Sí, contamos con opciones de pago para tratamientos seleccionados.\n\nP: ¿Atienden urgencias?\nR: Sí, según disponibilidad del día.",
  q15: "Valoración odontológica — $80.000 — Diagnóstico inicial y plan de tratamiento.\nLimpieza dental — desde $150.000 — Profilaxis y revisión general.\nOrtodoncia — precio según valoración — Tratamiento personalizado.",
  q16: "https://drive.google.com/demo-sonrisa-perfecta",
  q17: "No diagnosticar sin valoración profesional.\nNo recomendar medicamentos.\nNo compartir información privada de pacientes.",
  q18: "Mensualmente",
  q19: "Solo si el cliente envía audio",
  q20: "Voz genérica",
  q21: "No aplica: se utilizará voz genérica.",
  q22: "Sí, desde el inicio",
  q23: "Llamar cuando el paciente solicite agendar una valoración o necesite confirmar una cita. Presentarse como Valentina de Clínica Dental Sonrisa Perfecta.",
  q24: "Transferir a un humano ante urgencias, preguntas clínicas específicas, quejas, solicitudes de financiación o cambios de cita para el mismo día.",
  q25: "+573105556677 · coordinacion@sonrisaperfecta.demo",
  q26: "Responder e informar horario",
  q27: "Solo cuando pide algo específico",
  q28: "HubSpot",
  q29: "Sí, pero necesito ayuda",
  q30: "Sí, acceso completo",
  q31: "Laura Gómez · +573108887766 · laura@sonrisaperfecta.demo",
  q32: "Google Calendar para disponibilidad de citas y HubSpot para seguimiento de pacientes.",
};
