import type { OnboardingPlanSelection } from "@/types/onboarding";
import type { PlanCategory, PlanGroup } from "@/types/plan";

export const planGroups: PlanGroup[] = [
  {
    id: "ventas",
    label: "Agente de Ventas",
    icon: "AI",
    title: "Agente de Ventas WhatsApp",
    description: "responde, califica y cierra solo",
    plans: [
      {
        id: "starter",
        category: "ventas",
        name: "Starter",
        target: "Negocio local · Primeros pasos",
        setup: "$400 setup único",
        price: "250",
        period: "hasta 500 conversaciones/mes",
        features: [
          { label: "Bot WhatsApp básico" },
          { label: "5 flujos de respuesta" },
          { label: "Integración con Sheets" },
          { label: "Setup en 7 días · 2 cambios/mes" },
          { label: "Reporte mensual" },
          { label: "Audios de voz", included: false },
          { label: "Llamadas automáticas", included: false },
        ],
        ltv: "$3,400",
        accent: "petroleum",
      },
      {
        id: "growth",
        category: "ventas",
        name: "Growth",
        target: "PYME activa · Volumen medio",
        setup: "$2,500 setup único",
        price: "600",
        period: "hasta 3,000 conversaciones/mes",
        features: [
          { label: "Agente IA entrenado para tu negocio" },
          { label: "CRM + calificación de leads" },
          { label: "Audios con voz natural" },
          { label: "Llamadas automáticas" },
          { label: "Dashboard ROI en vivo" },
          { label: "5 cambios/mes" },
        ],
        ltv: "$9,700",
        accent: "green",
        featured: true,
      },
      {
        id: "scale",
        category: "ventas",
        name: "Scale",
        target: "Empresa · Alto volumen",
        setup: "$6,500 setup único",
        price: "1,200",
        period: "10,000+ conversaciones/mes",
        features: [
          { label: "Agente multi-tarea" },
          { label: "Integración ERP/CRM" },
          { label: "Voz + WhatsApp + web" },
          { label: "Llamadas premium" },
          { label: "SLA 24h · Reportes ejecutivos" },
          { label: "Mejoras ilimitadas" },
        ],
        ltv: "$20,900",
        accent: "wine",
      },
    ],
  },
  {
    id: "contenido",
    label: "Contenido IA",
    icon: "✦",
    title: "Contenido IA Automatizado",
    description: "posts, videos y redes en piloto automático",
    plans: [
      {
        id: "essential",
        category: "contenido",
        name: "Essential",
        target: "Marca local · 1-2 canales",
        setup: "$800 setup único",
        price: "350",
        period: "12 posts/mes · IG + FB",
        features: [
          { label: "12 posts/mes IG + FB" },
          { label: "Imágenes generadas con IA" },
          { label: "Calendario editorial" },
          { label: "Programación automática" },
          { label: "Reporte mensual" },
          { label: "Video / Reels", included: false },
          { label: "Ads pagados", included: false },
        ],
        ltv: "$5,000",
        accent: "petroleum",
      },
      {
        id: "professional",
        category: "contenido",
        name: "Professional",
        target: "PYME con marca activa",
        setup: "$1,800 setup único",
        price: "750",
        period: "24 posts/mes · 4 canales",
        features: [
          { label: "24 posts/mes · 4 canales" },
          { label: "4 reels/videos con IA" },
          { label: "Copys personalizados por canal" },
          { label: "Gestión comentarios IA" },
          { label: "Dashboard de métricas" },
        ],
        extraLabel: "+ además incluye",
        extraFeatures: [{ label: "2 campañas/mes ads" }, { label: "A/B testing automático" }],
        ltv: "$10,800",
        accent: "green",
        featured: true,
      },
      {
        id: "enterprise",
        category: "contenido",
        name: "Enterprise",
        target: "Mediana empresa · Multimarca",
        setup: "$3,500 setup único",
        price: "1,500",
        period: "60+ posts/mes · 5+ canales",
        features: [
          { label: "60+ posts/mes" },
          { label: "Video largo + reels" },
          { label: "5+ canales activos" },
          { label: "Email marketing con IA" },
          { label: "SEO de contenido" },
        ],
        extraLabel: "+ además incluye",
        extraFeatures: [
          { label: "Estrategia trimestral · Ads gestionados" },
          { label: "Reuniones semanales" },
        ],
        ltv: "$21,500",
        accent: "wine",
      },
    ],
  },
  {
    id: "combo",
    label: "Ventas + Contenido",
    icon: "◎",
    title: "Ventas + Contenido · Todo junto",
    description: "15% de descuento",
    plans: [
      {
        id: "combo-starter",
        category: "combo",
        name: "Combo Starter",
        target: "Negocio local · Todo en uno",
        setup: "$1,200 setup único (ahorra $200)",
        price: "510",
        period: "$600/mes por separado",
        extraLabel: "Agente Starter + Contenido Essential",
        features: [
          { label: "Bot WhatsApp · 500 conv/mes" },
          { label: "5 flujos · Integración Sheets" },
          { label: "12 posts/mes IG + FB" },
          { label: "Imágenes IA · Calendario editorial" },
          { label: "Programación automática" },
        ],
        ltv: "$8,400 · ahorras ~$90/mes",
        accent: "petroleum",
      },
      {
        id: "combo-growth",
        category: "combo",
        name: "Combo Growth",
        target: "PYME activa · Solución completa",
        setup: "$4,300 setup único (ahorra $700)",
        price: "1,147",
        period: "$1,350/mes por separado",
        extraLabel: "Agente Growth + Contenido Professional",
        features: [
          { label: "Agente IA · 3,000 conv/mes" },
          { label: "CRM + leads + audios + llamadas" },
          { label: "24 posts/mes · 4 canales" },
          { label: "4 reels/videos IA · Copys personalizados" },
          { label: "2 campañas ads · A/B testing" },
        ],
        ltv: "$20,500 · ahorras ~$203/mes",
        accent: "green",
        featured: true,
      },
      {
        id: "combo-scale",
        category: "combo",
        name: "Combo Scale",
        target: "Empresa · Máximo poder",
        setup: "$10,000 setup único (ahorra $1,500)",
        price: "2,295",
        period: "$2,700/mes por separado",
        extraLabel: "Agente Scale + Contenido Enterprise",
        features: [
          { label: "Agente multi-tarea · 10,000+ conv" },
          { label: "ERP/CRM · SLA 24h · Reportes ejecutivos" },
          { label: "60+ posts/mes · 5+ canales" },
          { label: "Video largo + email marketing + SEO" },
          { label: "Estrategia trimestral · Reuniones semanales" },
        ],
        ltv: "$42,400 · ahorras ~$405/mes",
        accent: "wine",
      },
    ],
  },
];

export function getOnboardingHref(servicio: PlanCategory, plan: string) {
  return `/onboarding?servicio=${encodeURIComponent(servicio)}&plan=${encodeURIComponent(plan)}`;
}

export function getOnboardingPlanSelection(
  servicio?: string,
  planId?: string,
): OnboardingPlanSelection | null {
  const group = planGroups.find((item) => item.id === servicio);
  const plan = group?.plans.find((item) => item.id === planId);

  if (!group || !plan) return null;

  return {
    servicio_interes: group.id,
    plan_interes: plan.id,
    servicio_label: group.label,
    plan_label: plan.name,
  };
}
